gateways:
    local:
        connection:
            type: duckdb
            database: db.db
    local_postgres:
        connection:
            type: postgres
            host: localhost
            database: ci
            user: postgres
            password: postgres
            port: 5432

default_gateway: local_postgres

model_defaults:
    dialect: postgres
